// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2GtAjs6T2aeOLd_KOJDgO59K4GAxLEwo',
    appId: '1:623336400723:web:856e3c532cd1dd0d3a23a6',
    messagingSenderId: '623336400723',
    projectId: 'laravel-notification-3d7e6',
    authDomain: 'laravel-notification-3d7e6.firebaseapp.com',
    storageBucket: 'laravel-notification-3d7e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-IyjJyDIXdjxeXSshJFmRJgsQtfcvDk',
    appId: '1:623336400723:android:e89705e059cf53753a23a6',
    messagingSenderId: '623336400723',
    projectId: 'laravel-notification-3d7e6',
    storageBucket: 'laravel-notification-3d7e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE29X_pfKzCeEjf6ZGjQN_Vovz70mLc1Q',
    appId: '1:623336400723:ios:709e8b342fdb07b93a23a6',
    messagingSenderId: '623336400723',
    projectId: 'laravel-notification-3d7e6',
    storageBucket: 'laravel-notification-3d7e6.appspot.com',
    iosClientId: '623336400723-6ok0gmm2ncuprgp2pv0tg7pgftrdrgs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE29X_pfKzCeEjf6ZGjQN_Vovz70mLc1Q',
    appId: '1:623336400723:ios:709e8b342fdb07b93a23a6',
    messagingSenderId: '623336400723',
    projectId: 'laravel-notification-3d7e6',
    storageBucket: 'laravel-notification-3d7e6.appspot.com',
    iosClientId: '623336400723-6ok0gmm2ncuprgp2pv0tg7pgftrdrgs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notification',
  );
}
